apiVersion: metacontroller.k8s.io/v1alpha1
kind: DecoratorController
metadata:
  name: chart
spec:
  resyncPeriodSeconds: 10
  resources:
  - apiVersion: k-processor.io/v1
    resource: charts
  attachments:
  - apiVersion: metacontroller.k8s.io/v1alpha1
    resource: compositecontrollers
    updateStrategy:
      method: InPlace
  hooks:
    sync:
      webhook:
        url: http://echoserver.test-payload.svc/chart-decorator
        timeout: 10s