apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: charts.k-processor.io
spec:
  group: k-processor.io
  scope: Namespaced
  names:
    plural: charts
    singular: chart
    kind: Chart
    shortNames: ["ch"]
    categories:
      - all
  versions:
  - name: v1
    served: true
    storage: true
    subresources:
      status: { }
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              repository:
                type: object
                properties:
                  uri:
                    type: string
                  sshKey:
                    type: string
                    nullable: true
                  secret:
                    type: object
                    nullable: true
                    properties:
                      name:
                        type: string
                      namespace:
                        type: string
                  revision:
                    type: string
                    default: "master"
                  refreshPeriod:
                    x-kubernetes-int-or-string: true
          status:
            type: object
            properties:
              commit:
                type: string
                nullable: true
              error:
                type: string
                nullable: true