apiVersion: v1
kind: Service
metadata:
  annotations:
    k-processor-name: Root.m1.c1[0]
  generateName: c1[0]-
spec:
  ports:
  - port: 82
    protocol: TCP
    targetPort: 9376
  selector:
    app.kubernetes.io/name: MyApp
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    k-processor-name: Root.m1.c1[1]
  generateName: c1[1]-
spec:
  ports:
  - port: 83
    protocol: TCP
    targetPort: 9376
  selector:
    app.kubernetes.io/name: MyApp
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    k-processor-name: Root.m1.c2
  generateName: c2-
spec:
  ports:
  - port: 81
    protocol: TCP
    targetPort: 9376
  selector:
    app.kubernetes.io/name: MyApp
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    k-processor-name: Root.m1.c2b
  generateName: c2b-
spec:
  ports:
  - port: 82
    protocol: TCP
    targetPort: 9376
  selector:
    app.kubernetes.io/name: MyApp